<pre>
 ____  __.            .__
|    |/ _|__ _________|__| __________
|      < |  |  \_  __ \  |/  ___/  _ \
|    |  \|  |  /|  | \/  |\___ (  <_> )
|____|__ \____/ |__|  |__/____  >____/
        \/                    \/

Maybe there are copies of me on countless world lines.
Maybe all their minds are connected, forming a single 'me'
That sound wonderful, don't you think? Being in all times and in all places.
- Kurisu Makise

web: <a href="https://kurikku.pw">kurikku.pw</a>
github: <a href="https://github.com/osukurikku/kuriso">github.com/osukurikku/kuriso</a>
discord: <a href="https://discord.gg/5uA3c76">discord.gg/5uA3c76</a>
status: <a href="https://status.kurikku.pw">status.kurikku.pw</a>
</pre>